version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - "POSTGRES_DB=pcdb"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    container_name: postgres_pcnew
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"

  web:
    build: .
    image: precocerto_webnew
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: precocerto_new
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A app1 worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
volumes:
  postgres_data:
