# Generated by Django 2.2.6 on 2019-10-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20191015_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='categoria',
            field=models.CharField(db_column='Categoria', max_length=200, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='preco',
            field=models.FloatField(db_column='Preço de Custo', verbose_name='Preço de Custo'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='produto',
            field=models.CharField(db_column='Produto', max_length=200, verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='total',
            field=models.FloatField(db_column='Total da venda', verbose_name='Total da Venda'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='unidades',
            field=models.IntegerField(db_column='Unidades Vendidas no Mês', verbose_name='Unidades Vendidas no Mẽs'),
        ),
    ]
