# Generated by Django 2.2.6 on 2019-10-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20191018_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='unidades',
            field=models.IntegerField(db_column='Unidades Vendidas no Mês', verbose_name='Unidades Vendidas no Mês'),
        ),
    ]
