# Generated by Django 2.2.6 on 2019-10-20 23:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_vendas_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='pub_date',
            field=models.DateTimeField(db_column='Data de Importação', default=datetime.datetime(2019, 10, 20, 23, 33, 2, 801145, tzinfo=utc), verbose_name='Data de Importação'),
        ),
    ]
