# Generated by Django 2.2.6 on 2019-10-21 03:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20191020_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacao',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Data da Importação'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='pub_date',
            field=models.DateTimeField(db_column='Data de Importação', default=datetime.datetime(2019, 10, 21, 3, 32, 38, 985568, tzinfo=utc), verbose_name='Data de Importação'),
        ),
    ]
