# Generated by Django 2.2.6 on 2019-10-21 04:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_auto_20191021_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='pub_date',
            field=models.DateTimeField(db_column='Data de Importação', default=datetime.datetime(2019, 10, 21, 4, 28, 35, 396627, tzinfo=utc), verbose_name='Data de Importação'),
        ),
    ]
