# Generated by Django 2.2.6 on 2019-10-21 05:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_auto_20191021_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='pub_date',
            field=models.DateTimeField(db_column='Data de Importação', default=datetime.datetime(2019, 10, 21, 5, 27, 52, 563757, tzinfo=utc), verbose_name='Data de Importação'),
        ),
    ]
