# Generated by Django 2.2.6 on 2019-10-21 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_auto_20191021_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='pub_date',
            field=models.DateTimeField(db_column='Data de Importação', default=datetime.datetime(2019, 10, 21, 7, 15, 11, 602424, tzinfo=utc), verbose_name='Data de Importação'),
        ),
    ]
