# Generated by Django 2.2.6 on 2019-10-21 07:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_auto_20191021_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacao',
            name='uploads',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='pub_date',
            field=models.DateTimeField(db_column='Data de Importação', default=datetime.datetime(2019, 10, 21, 7, 52, 29, 400797, tzinfo=utc), verbose_name='Data de Importação'),
        ),
    ]
